<?php
return array (
  'page' => '20',
  'status' => '1',
  'wechat' => NULL,
  'wechat_appId' => '',
  'wechat_token' => '',
  'wechat_encodingaes' => '',
  'wechat_secret' => '',
  'wechat_template_expire' => '',
  'room_release' => NULL,
  'room_release_condi' => '3',
  'room_release_allowed' => '5',
  'alicloud' => NULL,
  'alicloud_appId' => '',
  'alicloud_secret' => '',
  'luat' => NULL,
  'luat_uri' => '',
  'luat_appId' => '',
  'luat_secret' => '',
  'luat_account' => '',
  'luat_balance' => '',
);
